version: '3.8'
services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=12345aA!'
    ports:
      - '1433:1433'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
